### GET 
GET http://localhost:3001

### SIGNUP USER
POST http://localhost:3001/api/signup
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "password12"
}
### SIGNUP USER PRODUCTION
POST https://jwt-autentication.vercel.app/api/signup
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "password12"
}

### LOGIN USER
POST http://localhost:3001/api/signin
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "password12"
}

### Create Product
POST http://localhost:3001/api/product
Content-Type: application/json

{
    "title": "Iphone 12 PRO MAX",
    "description": "Latest Ipone Model",
    "qty": 3,
    "price": 12.3
}

### GET ALL PRODUCTS

GET http://localhost:3001/api/product


### UPDATE PRODUCT
PUT  http://localhost:3001/api/product/1
Content-Type: application/json

{
    "title": "NEW PRODUCT"
}


### DELETE PRODUCT
DELETE  http://localhost:3001/api/product/2